#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

/sbin/ofdown "$@"
. /etc/functions.sh
[ $# = 0 ] && { echo "  $0 <group>"; exit; }
[ "x$1" = "x-a" ] && {
	[ -e "/tmp/resolv.conf.auto" ] && rm /tmp/resolv.conf.auto
	config_cb() {
		[ ofswitch != "$1" -o -z "$2" ] || eval "$0 $2"
	}
	config_load openflow
	exit
}
include /lib/openflow

scan_ofinterfaces

setup_ofswitch $1

config_get dp "$1" dp

ifname=`dpctl show ${dp} |awk '/^ LOCAL.*addr/ {split($1,a,"[()]");print a[2]}'`

for dev in $ifname; do
	setup_ofinterface "$dev" "$1"
	sleep 1
	setup_ofsecchan "$dev" "$1"
done
